project_id = "jihwsnrzysbqdjldrmau"

[functions.chercheurs-api]
verify_jwt = true

[functions.publications-api]
verify_jwt = true

[functions.stats-dashboard]
verify_jwt = true

[functions.export-data]
verify_jwt = true

[functions.centres-api]
verify_jwt = false

[functions.provinces-api]
verify_jwt = false
